export default [
    { x: 5120, y: 2895, reward: "Tank Liner", notes: "Behind Tabby Plort Door and Phosphor Gordo" },
    { x: 4800, y: 3120, reward: "#1 Slime Stage", notes: "Top of the mountain" },
    { x: 5000, y: 2720, reward: "Heart Cell", notes: "In the wall" },
    { x: 5023, y: 2461, reward: "Hydro Turret", notes: "In sandy cave" },
    { x: 4930, y: 2230, reward: "Goldpetal Flowers", notes: "Outside of portal cave" },
    { x: 4868, y: 2654, reward: "Small Boulder", notes: "On top near feral slimes" },
    { x: 4057, y: 2696, reward: "Emerald Cypress Cluster", notes: "Behind Ember Valley portal, behind rock column facing sea" },
    { x: 4407, y: 3062, reward: "Emerald Cypress", notes: "In a tiny cave" },
    { x: 4235, y: 3532, reward: "Med Station", notes: "Below Starlight Strand portal" },
    { x: 4587, y: 3316, reward: "Power Chip", notes: "Cave near Starlight Strand portal" },
    { x: 5266, y: 3706, reward: "Rock Fragments", notes: "behind portal" },
    { x: 5309, y: 3525, reward: "Pink Warp Depot", notes: "Under the portal in a cave" },
    { x: 4796, y: 3080, reward: "Large Pink Bonsai", notes: "Next to the mountain" },
    { x: 4583, y: 2924, reward: "Overjoyed Statue", notes: "On top in clear view, near rocks" },
    { x: 3582, y: 4212, reward: "Rock Cluster", notes: "Near the sea" },
    { x: 4026, y: 5169, reward: "Azure Grass", notes: "Cliffside" },
    { x: 4900, y: 5812, reward: "Starbloom Flowers", notes: "High up, faces water" },
    { x: 5021, y: 4798, reward: "Tank Liner", notes: "Cave guarded by Honey Gordo and Phosphor Plort Doors" },
    { x: 4495, y: 4922, reward: "Storage Cell", notes: "Rock Plort Door cave" },
    { x: 5133, y: 5170, reward: "Cave Pillars", notes: "Angler Plort Door cave behind waterfall" },
    { x: 3952, y: 6442, reward: "Power Cell", notes: "On top near corals" },
    { x: 4400, y: 5909, reward: "Tall Violet Swirl Shroom", notes: "Rock Plort Door cave from the sand area below" },
    { x: 4253, y: 5500, reward: "Azure Shrubs", notes: "Hunter Plort Door from previous cave or Hunter Gordo" },
    { x: 4207, y: 5540, reward: "Novice Gordo Snare", notes: "Three Hunter Plort Doors" },
    { x: 5064, y: 5020, reward: "Sharp Boulder", notes: "Pond high up" },
    { x: 5430, y: 5895, reward: "Pink Glow Shrooms", notes: "Near Angler Gordo" },
    { x: 5649, y: 5990, reward: "Tank Liner", notes: "Top of the rock formation" },
    { x: 4743, y: 6266, reward: "Starlight Strand Portal", notes: "Under Flutter Gordo" },
    { x: 4693, y: 5400, reward: "Dash Boot Module", notes: "Top area, under trees" },
    { x: 4705, y: 5341, reward: "Root Tangle", notes: "From previous pod, go into hole" },
    { x: 4978, y: 6301, reward: "Spring Pad", notes: "Dark cave from above" },
    { x: 4036, y: 4420, reward: "Cheerful Statue", notes: "Above starting portal" },
    { x: 4053, y: 3903, reward: "Stalagmite Cluster", notes: "Under a ring, under the coral arch" },
    { x: 4410, y: 4266, reward: "Coastal Rock Pillar", notes: "Wedged into rock, facing the sea" },
    { x: 4943, y: 4634, reward: "Veggie Slime Bait", notes: "On top between two mountains" },
    { x: 4848, y: 4758, reward: "Large Pink Coral Columns", notes: "Honey Gordo cave, close to sea level down" },
    { x: 4595, y: 5863, reward: "Azure Mangrove", notes: "On top, hidden behind ring structure" },
    { x: 4508, y: 4880, reward: "Violet Warp Depot", notes: "Under tree branch, high up near rocks" },
    { x: 3402, y: 2499, reward: "Storage Cell", notes: "Batty Plort Door under portal" },
    { x: 2912, y: 2505, reward: "Meat Slime Bait", notes: "Inside stone cylinder, on top" },
    { x: 2613, y: 2431, reward: "Dash Pad", notes: "Inside stone cylinder, on top" },
    { x: 2341, y: 2287, reward: "Amber Cypress Cluster", notes: "Near a group of rocks" },
    { x: 2341, y: 2130, reward: "Amber Cypress", notes: "Wedged between stone cylinders" },
    { x: 2258, y: 1870, reward: "Heart Cell", notes: "Under flat rock, stairs leading to it" },
    { x: 2314, y: 1907, reward: "Happy Statue", notes: "Cave, near sea level" },
    { x: 2168, y: 1141, reward: "Blue Warp Depot", notes: "Encased in stone below Tabby Gordo" },
    { x: 2409, y: 1471, reward: "Sunfire Daisies", notes: "Ledge, surrounded by tall rocks" },
    { x: 2885, y: 1448, reward: "Cinder Spike Blossoms", notes: "Open cliffside facing sea" },
    { x: 3123, y: 2161, reward: "Jetpack Drive", notes: "Above geyser blocked by Rock Gordo in coral cave" },
    { x: 2861, y: 1980, reward: "Azure Glow Shrooms", notes: "Top of the sandy cave, area opened with 3 Boom Plort Statues" },
    { x: 2573, y: 2692, reward: "Medium Pink Coral Columns", notes: "Angler area, behind coral column" },
    { x: 2431, y: 2863, reward: "Gnarled Ashwood", notes: "Under flat rock near sea" },
    { x: 2336, y: 2659, reward: "Vac Tank", notes: "In pond on top of waterfall" },
    { x: 2064, y: 2823, reward: "Stalagmite", notes: "Top of volcanic cave, near Pomegranite tree" },
    { x: 1962, y: 2319, reward: "Grey Warp Depot", notes: "On top of the highest magma column in the area" },
    { x: 1730, y: 2213, reward: "Fruit Slime Bait", notes: "Secret cave high up, hidden by leaves" },
    { x: 1533, y: 2407, reward: "Medium Palm", notes: "Ledge near mountain, in open view" },
    { x: 1576, y: 2697, reward: "Tall Magma Clump", notes: "Near slime statues" },
    { x: 1706, y: 2897, reward: "Magma Pool", notes: "Down near geyser" },
    { x: 1816, y: 3025, reward: "Medium Red Ashwood", notes: "Cliffside facing sea, end of magma area" },
    { x: 1066, y: 2393, reward: "Ember Valley Portal", notes: "Behind Boom Gordo, top pod" },
    { x: 1066, y: 2350, reward: "Strange Diamond", notes: "Behind Boom Gordo, bottom pod" }
]